# Linear Algebra

In [1]:
import numpy as np

2.1 Scalars, Vectors, Matrices and Tensors

Key: Scalars, Vectors, Matrices, Tensors, Broadcasting, Transpose

In [47]:
#Scalars
a=5
#Vectors
x=np.reshape([5, 6, 7, 8, 9], (5, 1))
#Matrices
y1=np.random.rand(2, 3) #peramiters: (row, coloum)
y2=np.random.randint(3, 10) ##peramiters: (min value, max value) #Only randint formate and it is for int
y3=np.random.randint(11, size=(2, 3)) ##peramiters: (max value, (row, coloum))
#Tensors
z= np.random.rand(2,3,4)

In [55]:
a=np.random.randint(10, size=(2, 3))
b=np.random.randint(10, size=(2, 3))
c=a+b
d=5*a+10
print("a: \n",a)
print("b: \n",b)
print("c: \n",c)
print("d: \n",d)

a: 
 [[1 6 9]
 [6 7 5]]
b: 
 [[3 1 5]
 [8 7 8]]
c: 
 [[ 4  7 14]
 [14 14 13]]
d: 
 [[15 40 55]
 [40 45 35]]


In [59]:
#Broadcasting
#Example 1
a=np.random.randint(10, size=(2, 3)) #Maqtrix
b=np.random.randint(10, size=(1, 3))
c=a+b
print("Example 1")
print("a: \n",a)
print("b: \n",b)
print("c: \n",c)
#Example 2
a=np.random.randint(10, size=(2, 3)) #Maqtrix
b=a+10
print("Example 2")
print("a: \n",a)
print("b: \n",b)

Example 1
a: 
 [[6 4 8]
 [1 8 2]]
b: 
 [[2 6 3]]
c: 
 [[ 8 10 11]
 [ 3 14  5]]
Example 2
a: 
 [[1 2 3]
 [2 6 0]]
b: 
 [[11 12 13]
 [12 16 10]]


In [64]:
#Transpose
a=np.random.randint(10, size=(2, 3))
aT1=np.reshape(a, (3, 2))
aT2=np.transpose(a)
print("a: \n",a)
print("aT1: \n",aT1) #Not Transpose
print("aT2: \n",aT2) #Transpose

a: 
 [[9 0 3]
 [1 1 5]]
aT1: 
 [[9 0]
 [3 1]
 [1 5]]
aT2: 
 [[9 1]
 [0 1]
 [3 5]]


2.2 Multiplying Matrices and Vectors

In [72]:
a=np.random.randint(10, size=(2, 3))
b=np.random.randint(10, size=(2, 3))
c=np.random.randint(10, size=(2, 3))
print("a: \n",a)
print("b: \n",b)
print("c: \n",c)
print("a(b+c): \n",a*(b+c))
print("ab+ac: \n",(a*b)+(a*c))
print("a*b: \n", a*b) # Element wise
aT=np.transpose(a)
bT=np.transpose(b)
print("aT*b: \n",np.dot(aT,b)) #Real Mul Matrix (col x row)
print("bT*a: \n",np.dot(bT,a)) #Real Mul Matrix (col x row)

a: 
 [[4 6 7]
 [8 7 4]]
b: 
 [[8 7 2]
 [6 4 0]]
c: 
 [[9 0 4]
 [3 3 1]]
a(b+c): 
 [[68 42 42]
 [72 49  4]]
ab+ac: 
 [[68 42 42]
 [72 49  4]]
a*b: 
 [[32 42 14]
 [48 28  0]]
aT*b: 
 [[80 60  8]
 [90 70 12]
 [80 65 14]]
bT*a: 
 [[80 90 80]
 [60 70 65]
 [ 8 12 14]]
