# Linear Algebra

In [87]:
import numpy as np

2.1 Scalars, Vectors, Matrices and Tensors

In [88]:
#Scalars
a=5
#Vectors
x=np.reshape([5, 6, 7, 8, 9], (5, 1))
#Matrices
y1=np.random.rand(2, 3) #peramiters: (row, coloum)
y2=np.random.randint(3, 10) ##peramiters: (min value, max value) #Only randint formate and it is for int
y3=np.random.randint(11, size=(2, 3)) ##peramiters: (max value, (row, coloum))
#Tensors
z= np.random.rand(2,3,4)

In [89]:
a=np.random.randint(10, size=(2, 3))
b=np.random.randint(10, size=(2, 3))
c=a+b
d=5*a+10
print("a: \n",a)
print("b: \n",b)
print("c: \n",c)
print("d: \n",d)

a: 
 [[0 4 6]
 [7 6 2]]
b: 
 [[9 6 8]
 [4 7 2]]
c: 
 [[ 9 10 14]
 [11 13  4]]
d: 
 [[10 30 40]
 [45 40 20]]


In [90]:
#Broadcasting
#Example 1
a=np.random.randint(10, size=(2, 3)) #Maqtrix
b=np.random.randint(10, size=(1, 3))
c=a+b
print("Example 1")
print("a: \n",a)
print("b: \n",b)
print("c: \n",c)
#Example 2
a=np.random.randint(10, size=(2, 3)) #Maqtrix
b=a+10
print("Example 2")
print("a: \n",a)
print("b: \n",b)

Example 1
a: 
 [[1 7 5]
 [5 3 7]]
b: 
 [[3 3 0]]
c: 
 [[ 4 10  5]
 [ 8  6  7]]
Example 2
a: 
 [[7 3 7]
 [3 7 1]]
b: 
 [[17 13 17]
 [13 17 11]]


In [91]:
#Transpose
a=np.random.randint(10, size=(2, 3))
aT1=np.reshape(a, (3, 2))
aT2=np.transpose(a)
print("a: \n",a)
print("aT1: \n",aT1) #Not Transpose
print("aT2: \n",aT2) #Transpose

a: 
 [[7 7 3]
 [4 4 2]]
aT1: 
 [[7 7]
 [3 4]
 [4 2]]
aT2: 
 [[7 4]
 [7 4]
 [3 2]]


2.2 Multiplying Matrices and Vectors

In [92]:
a=np.random.randint(10, size=(2, 3))
b=np.random.randint(10, size=(2, 3))
c=np.random.randint(10, size=(2, 3))
print("a: \n",a)
print("b: \n",b)
print("c: \n",c)
print("a(b+c): \n",a*(b+c))
print("ab+ac: \n",(a*b)+(a*c))
print("a*b: \n", a*b) # Element wise
aT=np.transpose(a)
bT=np.transpose(b)
print("aT*b: \n",np.dot(aT,b)) #Real Mul Matrix (col x row)
print("bT*a: \n",np.dot(bT,a)) #Real Mul Matrix (col x row)

a: 
 [[0 6 6]
 [9 8 9]]
b: 
 [[0 7 5]
 [3 5 6]]
c: 
 [[0 6 1]
 [4 7 8]]
a(b+c): 
 [[  0  78  36]
 [ 63  96 126]]
ab+ac: 
 [[  0  78  36]
 [ 63  96 126]]
a*b: 
 [[ 0 42 30]
 [27 40 54]]
aT*b: 
 [[27 45 54]
 [24 82 78]
 [27 87 84]]
bT*a: 
 [[27 24 27]
 [45 82 87]
 [54 78 84]]


In [93]:
a=np.random.randint(10, size=(2, 3))
b=np.random.randint(10, size=(3, 1))
c=np.dot(a,b)
print("a: \n",a) #Matrix
print("b: \n",b) #Vector
print("c: \n",c) #Vector

a: 
 [[7 6 0]
 [4 2 2]]
b: 
 [[6]
 [5]
 [2]]
c: 
 [[72]
 [38]]


2.3 Identity abd Invers Matrices

In [94]:
a=np.identity(3)
print("a: \n",a) #I3 in float values
b=np.identity(3).astype(int)
print("b: \n",b) #I3 in int values

a: 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
b: 
 [[1 0 0]
 [0 1 0]
 [0 0 1]]


In [100]:
a=np.random.rand(3, 3)
print("a: \n",a)
b=np.linalg.inv(a) #inverse of a
print("b: \n",b)

a: 
 [[0.24989051 0.11101298 0.79884774]
 [0.88361533 0.69446368 0.78248793]
 [0.20076189 0.99878021 0.42886804]]
b: 
 [[-1.07936318  1.67419141 -1.04411541]
 [-0.49507566 -0.11873243  1.13880429]
 [ 1.65824145 -0.50721018  0.16835809]]


In [105]:
i=np.dot(b,a)
print("i: (in float) \n",i)
print("i: (in int) \n",i.astype(int))

i: (in float) 
 [[ 1.00000000e+00 -1.15746183e-16  1.11131214e-16]
 [ 6.62518573e-18  1.00000000e+00  3.04499641e-17]
 [-6.99371860e-17 -3.36293585e-17  1.00000000e+00]]
i: (in int) 
 [[1 0 0]
 [0 1 0]
 [0 0 0]]
